### ISSUE TITLE
Unsatisfiable result for easily satisfiable MaxSAT instance

### ISSUE THREAD

**Issue by progirep** [psaikko/LMHS#1]
So I a compiled the latest version of LMHS using CPLEX 12.8.0, and it compiled successfully, but I am getting some results that I cannot explain. I used the following (partial) MaxSAT instance:

```
p wcnf 124 225 15
1 -1 0
1 -2 0
1 -3 0
1 -4 0
1 -5 0
1 -6 0
1 -7 0
1 -8 0
1 -9 0
1 -10 0
1 -11 0
1 -12 0
1 -13 0
1 -14 0
1 -15 0
1 -16 0
1 -17 0
1 -18 0
1 -19 0
1 -20 0
1 -21 0
1 -22 0
1 -23 0
1 -24 0
1 -25 0
1 -26 0
1 -27 0
1 -28 0
1 -29 0
1 -30 0
1 -31 0
1 -32 0
1 -33 0
1 -34 0
1 -35 0
1 -36 0
1 -37 0
1 -38 0
1 -39 0
1 -40 0
1 -41 0
1 -42 0
1 -43 0
1 -44 0
1 -45 0
1 -46 0
1 -47 0
1 -48 0
1 -49 0
1 -50 0
1 -51 0
1 -52 0
1 -53 0
1 -54 0
1 -55 0
1 -56 0
1 -57 0
1 -58 0
1 -59 0
1 -60 0
1 -61 0
1 -62 0
1 -63 0
1 -64 0
1 -65 0
1 -66 0
1 -67 0
1 -68 0
1 -69 0
1 -70 0
1 -71 0
1 -72 0
1 -73 0
1 -74 0
1 -75 0
1 -76 0
1 -77 0
1 -78 0
1 -79 0
1 -80 0
1 -81 0
1 -82 0
1 -83 0
1 -84 0
1 -85 0
1 -86 0
1 -87 0
1 -88 0
1 -89 0
1 -90 0
1 -91 0
1 -92 0
1 -93 0
1 -94 0
1 -95 0
1 -96 0
1 -97 0
1 -98 0
1 -99 0
1 -100 0
1 -101 0
1 -102 0
1 -103 0
1 -104 0
1 -105 0
1 -106 0
1 -107 0
1 -108 0
1 -109 0
1 -110 0
1 -111 0
1 -112 0
1 -113 0
1 -114 0
1 -115 0
1 -116 0
1 -117 0
1 -118 0
1 -119 0
1 -120 0
1 -121 0
1 -122 0
1 -123 0
1 -124 0
15 3 0
15 2 0
15 4 0
15 1 0
15 7 0
15 6 0
15 11 0
15 5 0
15 14 0
15 10 0
15 13 0
15 15 0
15 27 0
15 25 0
15 26 0
15 58 0
15 57 0
15 49 0
15 29 0
15 28 0
15 24 0
15 22 0
15 70 0
15 23 0
15 66 0
15 74 0
15 68 0
15 19 0
15 80 0
15 76 0
15 18 0
15 59 0
15 60 0
15 17 0
15 75 0
15 77 0
15 42 0
15 41 0
15 43 0
15 83 0
15 50 0
15 84 0
15 62 0
15 63 0
15 64 0
15 82 0
15 85 0
15 87 0
15 56 0
15 40 0
15 44 0
15 61 0
15 47 0
15 48 0
15 39 0
15 45 0
15 38 0
15 21 0
15 20 0
15 69 0
15 8 0
15 9 0
15 12 0
15 16 0
15 30 0
15 31 0
15 32 0
15 35 0
15 34 0
15 33 0
15 81 0
15 86 0
15 88 0
15 36 0
15 46 0
15 37 0
15 52 53 0
15 78 79 0
15 54 55 0
15 51 53 0
15 65 78 0
15 55 67 0
15 72 73 0
15 71 73 0
15 51 52 0
15 65 79 0
15 54 67 0
15 71 72 0
15 90 91 92 0
15 95 96 97 0
15 89 93 94 0
15 117 120 121 0
15 106 107 108 0
15 105 109 124 0
15 113 114 115 0
15 116 122 123 0
15 110 111 112 0
15 100 101 118 0
15 98 99 119 0
15 102 103 104 0
15 65 76 78 79 0
```

LMHS-int gives me an "s UNSATISFIABLE" result, which makes little sense to me, as all hard constraints in the instance only consist of positive literals, so there is at the very least the solution in which all variables are set to TRUE. It would be great to get some insight on why this is happening.

**Comment by psaikko** [comment]
Hi, 

I had a look at this and it is caused by a hard clause "top" weight (15) that is less than the sum of all soft clause weights. In this case the hard clauses should be marked with a weight 125 or greater. 

I'll add some check to the solver to prevent confusing behavior in this case.

**Comment by progirep** [comment]
Thanks for your reply! I see that this is caused by the rules of the MaxSAT competition: while they define that hard clauses are those that have the corresponding weight, there is also the addition that tools can assume what you wrote, i.e., that every hard clause has a weight >= the sum of weights of the soft clauses. So LMHS makes use of this addition here. That's good to know. I didn't catch this as the 2016 version of LMHS (with minisat as solver) does not seem to make use of this addition, and that's also true for the Maxino solver.

Again, thanks for clarifying this.
